(function(a){a.fn.hoverIntent=function(b,c,g){var d={interval:100,sensitivity:7,timeout:0},d="object"===typeof b?a.extend(d,b):a.isFunction(c)?a.extend(d,{over:b,out:c,selector:g}):a.extend(d,{over:b,out:b,selector:c}),e,m,f,p,l=function(a){e=a.pageX;m=a.pageY},h=function(c,b){b.hoverIntent_t=clearTimeout(b.hoverIntent_t);if(Math.abs(f-e)+Math.abs(p-m)<d.sensitivity)return a(b).off("mousemove.hoverIntent",l),b.hoverIntent_s=1,d.over.apply(b,[c]);f=e;p=m;b.hoverIntent_t=setTimeout(function(){h(c,b)},
d.interval)};b=function(c){var b=jQuery.extend({},c),k=this;k.hoverIntent_t&&(k.hoverIntent_t=clearTimeout(k.hoverIntent_t));"mouseenter"==c.type?(f=b.pageX,p=b.pageY,a(k).on("mousemove.hoverIntent",l),1!=k.hoverIntent_s&&(k.hoverIntent_t=setTimeout(function(){h(b,k)},d.interval))):(a(k).off("mousemove.hoverIntent",l),1==k.hoverIntent_s&&(k.hoverIntent_t=setTimeout(function(){k.hoverIntent_t=clearTimeout(k.hoverIntent_t);k.hoverIntent_s=0;d.out.apply(k,[b])},d.timeout)))};return this.on({"mouseenter.hoverIntent":b,
"mouseleave.hoverIntent":b},d.selector)}})(jQuery);
(function(a){var b,c=/iPhone|iPad|iPod/i.test(navigator.userAgent);c&&a(window).load(function(){a("body").children().on("click",a.noop)});var g,d=document.documentElement.style;g="behavior"in d&&"fill"in d&&/iemobile/i.test(navigator.userAgent);var e=function(a,c){var b="sf-js-enabled";c.cssArrows&&(b+=" sf-arrows");a.toggleClass(b)},m=function(a){var c=a.css("ms-touch-action");a.css("ms-touch-action","pan-y"===c?"auto":"pan-y")},f=function(c){var b=a(this),e=b.siblings(c.data.popUpSelector);0<e.length&&
e.is(":hidden")&&(b.one("click.superfish",!1),"MSPointerDown"===c.type?b.trigger("focus"):a.proxy(p,b.parent("li"))())},p=function(){var c=a(this),b=n(c);clearTimeout(b.sfTimer);c.siblings().superfish("hide").end().superfish("show")},l=function(){var b=a(this),k=n(b);c?a.proxy(h,b,k)():(clearTimeout(k.sfTimer),k.sfTimer=setTimeout(a.proxy(h,b,k),k.delay))},h=function(c){c.retainPath=-1<a.inArray(this[0],c.$path);this.superfish("hide");this.parents("."+c.hoverClass).length||(c.onIdle.call(this.closest(".sf-js-enabled")),
c.$path.length&&a.proxy(p,c.$path)())},n=function(a){return a.closest(".sf-js-enabled").data("sf-options")};b={hide:function(c){if(this.length){var b=n(this);if(!b)return this;var e=!0===b.retainPath?b.$path:"",e=this.find("li."+b.hoverClass).add(this).not(e).removeClass(b.hoverClass).children(b.popUpSelector),f=b.speedOut;c&&(e.show(),f=0);b.retainPath=!1;b.onBeforeHide.call(e);e.stop(!0,!0).animate(b.animationOut,f,function(){var c=a(this);b.onHide.call(c)})}return this},show:function(){var a=n(this);
if(!a)return this;var c=this.addClass(a.hoverClass).children(a.popUpSelector);a.onBeforeShow.call(c);c.stop(!0,!0).animate(a.animation,a.speed,function(){a.onShow.call(c)});return this},destroy:function(){return this.each(function(){var c=a(this),b=c.data("sf-options"),f;if(!b)return!1;f=c.find(b.popUpSelector).parent("li");clearTimeout(b.sfTimer);e(c,b);f.children("a").toggleClass("sf-with-ul");m(c);c.off(".superfish").off(".hoverIntent");f.children(b.popUpSelector).attr("style",function(a,c){return c.replace(/display[^;]+;?/g,
"")});b.$path.removeClass(b.hoverClass+" sf-breadcrumb").addClass(b.pathClass);c.find("."+b.hoverClass).removeClass(b.hoverClass);b.onDestroy.call(c);c.removeData("sf-options")})},init:function(b){return this.each(function(){var d=a(this);if(d.data("sf-options"))return!1;var h=a.extend({},a.fn.superfish.defaults,b),n=d.find(h.popUpSelector).parent("li"),q;q=d.find("li."+h.pathClass).slice(0,h.pathLevels).addClass(h.hoverClass+" sf-breadcrumb").filter(function(){return a(this).children(h.popUpSelector).hide().show().length}).removeClass(h.pathClass);
h.$path=q;d.data("sf-options",h);e(d,h);n.children("a").toggleClass("sf-with-ul");m(d);q="li:has("+h.popUpSelector+")";if(a.fn.hoverIntent&&!h.disableHI)d.hoverIntent(p,l,q);else d.on("mouseenter.superfish",q,p).on("mouseleave.superfish",q,l);q="MSPointerDown.superfish";c||(q+=" touchend.superfish");g&&(q+=" mousedown.superfish");d.on("focusin.superfish","li",p).on("focusout.superfish","li",l).on(q,"a",h,f);n.not(".sf-breadcrumb").superfish("hide",!0);h.onInit.call(this)})}};a.fn.superfish=function(c,
e){return b[c]?b[c].apply(this,Array.prototype.slice.call(arguments,1)):"object"!==typeof c&&c?a.error("Method "+c+" does not exist on jQuery.fn.superfish"):b.init.apply(this,arguments)};a.fn.superfish.defaults={popUpSelector:"ul,.sf-mega",hoverClass:"sfHover",pathClass:"overrideThisToUse",pathLevels:1,delay:800,animation:{opacity:"show"},animationOut:{opacity:"hide"},speed:"normal",speedOut:"fast",cssArrows:!0,disableHI:!1,onInit:a.noop,onBeforeShow:a.noop,onShow:a.noop,onBeforeHide:a.noop,onHide:a.noop,
onIdle:a.noop,onDestroy:a.noop};a.fn.extend({hideSuperfishUl:b.hide,showSuperfishUl:b.show})})(jQuery);
(function(a){a.fn.stupidtable=function(b){return this.each(function(){var c=a(this);b=b||{};b=a.extend({},a.fn.stupidtable.default_sort_fns,b);c.data("sortFns",b);c.on("click.stupidtable","thead th",function(){a(this).stupidsort()})})};a.fn.stupidsort=function(b){var c=a(this),g=0,d=a.fn.stupidtable.dir,e=c.closest("table"),m=c.data("sort")||null;if(null!==m){c.parents("tr").find("th").slice(0,a(this).index()).each(function(){var c=a(this).attr("colspan")||1;g+=parseInt(c,10)});var f;1==arguments.length?
f=b:(f=b||c.data("sort-default")||d.ASC,c.data("sort-dir")&&(f=c.data("sort-dir")===d.ASC?d.DESC:d.ASC));e.trigger("beforetablesort",{column:g,direction:f});e.css("display");setTimeout(function(){var b=[],l=e.data("sortFns")[m],h=e.children("tbody").children("tr");h.each(function(c,e){var d=a(e).children().eq(g),f=d.data("sort-value");"undefined"===typeof f&&(f=d.text(),d.data("sort-value",f));b.push([f,e])});b.sort(function(c,a){return l(c[0],a[0])});f!=d.ASC&&b.reverse();h=a.map(b,function(c){return c[1]});
e.children("tbody").append(h);e.find("th").data("sort-dir",null).removeClass("sorting-desc sorting-asc");c.data("sort-dir",f).addClass("sorting-"+f);e.trigger("aftertablesort",{column:g,direction:f});e.css("display")},10);return c}};a.fn.updateSortVal=function(b){var c=a(this);c.is("[data-sort-value]")&&c.attr("data-sort-value",b);c.data("sort-value",b);return c};a.fn.stupidtable.dir={ASC:"asc",DESC:"desc"};a.fn.stupidtable.default_sort_fns={"int":function(a,c){return parseInt(a,10)-parseInt(c,10)},
"float":function(a,c){return parseFloat(a)-parseFloat(c)},string:function(a,c){return a.localeCompare(c)},"string-ins":function(a,c){a=a.toLocaleLowerCase();c=c.toLocaleLowerCase();return a.localeCompare(c)}}})(jQuery);
var stblDataTypes={returnBlanks:function(a,b,c){a=$.trim(a.toString().replace("-",""));b=$.trim(b.toString().replace("-",""));return""==a||"-"==a?1:""==b||"-"==b?-1:c(a,b)},strMoveBlanks:function(a,b){return stblDataTypes.returnBlanks(a,b,function(a,b){return a<b?-1:a>b?1:0})},strMoveBlanksDesc:function(a,b){return stblDataTypes.returnBlanks(a,b,function(a,b){return a<b?1:a>b?-1:0})},intMoveBlanks:function(a,b){return stblDataTypes.returnBlanks(a,b,function(a,b){return parseInt(a,10)-parseInt(b,10)})},
intMoveBlanksDesc:function(a,b){return stblDataTypes.returnBlanks(a,b,function(a,b){return parseInt(b,10)-parseInt(a,10)})}};
(function(a){var b=["odd","even"],c=[],g={text:{selector:'input[type="text"]',event:"keyup"},select:{selector:"select",event:"change"},checkbox:{selector:'input[type="checkbox"]',event:"click"}},d={init:function(b){b=a.extend({controlPanel:null,handleSort:!0},b);var m=a(this);return this.each(function(){var f=window.location.hash.replace("#!","");if(0<f.length){var f=f.split("&"),p;for(p in f){var l=f[p].split("=");a('[data-filter-hash="'+l[0]+'"]',b.controlPanel).val(l[1])}}for(p in g)a(g[p].selector,
b.controlPanel).each(function(){var b=a(this);c.push(b);b.on(g[p].event,function(){d.createAndRunFilters(m)})});d.createAndRunFilters(m)})},filter:function(b){b=a.extend({filters:[],handleSort:!0},b);return this.each(function(){var c=a(this);c.trigger("beforetablefilter");if(b.handleSort)c.on("aftertablesort",function(a,b){d.handleRowsThenStripe(c,function(a){return!a.hasClass("hidden")})});setTimeout(function(){d.handleRowsThenStripe(c,function(a){for(var c=0,d=b.filters.length;c<d;c++){for(var h=
b.filters[c].columns,m=b.filters[c].value.toString().toLowerCase(),g=!1,k=0,u=h.length;k<u;k++){var t=a.find("td").eq(h[k]),q=t.data("filter-val");0<=(void 0===q?t.text():q).toString().toLowerCase().indexOf(m)&&(g=!0)}if(!g)return!1}return!0});c.trigger("aftertablefilter")},10)})},handleRowsThenStripe:function(c,d){var f=0,g=c.find("> tbody");g.each(function(){var c=g.clone();c.find("> tr").each(function(){var c=a(this),e=d(c);c.removeClass(b.join(" "));e?(c.removeClass("hidden"),c.addClass(b[f]),
f=1-f):c.addClass("hidden")});g.replaceWith(c)})},createAndRunFilters:function(a){for(var b=[],f=0,p=c.length;f<p;f++){var l=c[f],h=l.data("filter-col");if(void 0!==h){var h=h.toString().split(","),n="";c[f].is(g.checkbox.selector)?c[f].is(":checked")&&(n=l.data("filter-val")):n=l.val();b.push({columns:h,value:n})}}d.filter.apply(a,[{filters:b}])}};a.fn.filtable=function(c){if("filter"===c)return d.filter.apply(this,Array.prototype.slice.call(arguments,1));if("object"!==typeof c&&c)a.error("Unknown method `"+
c+"` on jQuery.filtable");else return d.init.apply(this,arguments)}})(jQuery);
(function(a){a.extend({localDb:function(b,c){function g(d){a.ajax({url:b+d,success:function(b){a:{var g={};try{g=JSON.parse(b)}catch(l){a.error("Server response was not JSON");break a}e[d]=g;localStorage[d]=b;b=JSON.parse(localStorage.versions);b[d]=c;localStorage.versions=JSON.stringify(b)}},error:function(){a.error("Error fetching data from server")}})}function d(a,b){var g=JSON.parse(localStorage.versions),l=!0,h;for(h in a){var n=a[h],r=localStorage[n];!r||g[n]<c?l=!1:e[n]||(e[n]=JSON.parse(r))}l?
setTimeout(b,10):setTimeout(function(){d(a,b)},1E3)}var e={};localStorage||(localStorage={});return{load:function(a,b){var e=[];if(localStorage.versions){var l=JSON.parse(localStorage.versions),h;for(h in a){var n=a[h];(!localStorage[n]||l[n]<c)&&e.push(n)}}else localStorage.versions="{}",e=a;for(h in e)g(e[h]);d(a,b)},table:function(a){return e[a]}}}})})(jQuery);
(function(a){a.fn.svTabs=function(b){return this.each(function(){b=a.extend({hideSingle:!1,equalHeight:!1},b);var c=a(this),g=c.find("> .svtabs-tab-list > .svtabs-tab"),d=c.find("> .svtabs-panel-list > .svtabs-panel"),e=g.length,m=d.length;if(e!==m)a.error("Number of tabs ("+e+") does not match number of panels ("+m+")");else{g.each(function(c){var e=a("a",a(this)),f=e.attr("href");b.equalHeight&&d.eq(c).css({position:"absolute"});e.on("click",function(b){g.removeClass("svtabs-active");d.addClass("svtabs-panel-hidden");
g.eq(c).addClass("svtabs-active");a(f).removeClass("svtabs-panel-hidden");b.preventDefault()})});1==e&&b.hideSingle&&c.addClass("svtabs-onetab");if(b.equalHeight){var f=0;d.each(function(c){c=a(this).outerHeight();c>f&&(f=c)});c.find(">.svtabs-panel-list").height(f)}g.eq(0).find("a").click()}})}})(jQuery);
(function(a){a.extend({svModal:function(b){var c=null;(function(b){c=a('<div id="'+b+'" class="whiteout"><div class="modal"><span class="modal-close" title="Close">&times;</span><h3 class="modal-title"></h3><div class="modal-content"></div></div></div>').appendTo("body");a(".whiteout, .modal-close").click(function(a){a.target==this&&c&&c.fadeOut()})})(b);return{inject:function(b,d){c&&(a(".modal-title",c).html(d),a(".modal-content",c).html(b))},show:function(){c&&c.fadeIn()},close:function(){c&&c.fadeOut()}}}})})(jQuery);
String.prototype.contains=function(a){return-1!=this.toLowerCase().indexOf(a.toLowerCase())};
var htsc=function(a){return a.replace(/&/gi,"&amp;").replace(/</gi,"&lt;").replace(/>/gi,"&gt;").replace(/"/gi,"&quot;")},makeModalContent=function(a){var b=a.parents("table").eq(0),c=b.data("pkname"),b="http://pokemondb.net/pokedex/"+b.data("pkalias");a=a.attr("href");var g='[URL="'+b+'"][IMG]'+a+"[/IMG][/URL]",d="[!["+c+"]("+a+")]("+b+")";return'<div class="figure"><img class="sprite-share-img" src="'+a+'" alt="'+c+'"></div><p class="small aside">Copy the code below to display this sprite on your web page, blog or forum signature.</p><label class="small">HTML code (websites):</label><br><input type="text" readonly class="input-text" value="'+
htsc('<a href="'+b+'"><img src="'+a+'" alt="'+c+'"></a>')+'"><br><label class="small">BBcode (forums and forum signatures):</label><br><input type="text" readonly class="input-text" value="'+htsc(g)+'"><br> <label class="small">Markdown (for Pok\u00e9Base):</label><br><input type="text" readonly class="input-text" value="'+htsc(d)+'">'};
$(function(){$(".main-menu-list > li > a").removeAttr("href");$(".main-menu-list").superfish({delay:800,speed:300,speedOut:300,cssArrows:!1});var a={tmplResult:function(a){var b="egg_group"==a.type?"mechanics/egg-groups":a.type,d=a.type.charAt(0).toUpperCase()+a.type.substr(1).replace("_"," ");return'<div class="sitesearch-results-item"><a class="ent-name" href="/'+b+"/"+a.alias+'">'+a.name+'</a> <small class="aside">('+d+")</small></div>"},outputResults:function(b){if(0===b.length)$("#sitesearch-results").slideUp();
else{entHtml="";for(var g in b)entHtml+=a.tmplResult(b[g]);$("#sitesearch-results").html(entHtml).slideDown()}},appMain:function(){$("#sitesearch").on("keyup focus",function(){var c=$(this).val();if(1<c.length){var g=b.table("searchdata"),d=[],e;for(e in g){for(var m in g[e]){var f=g[e][m];if(f[0].contains(c)||f[1].contains(c))if(d.push({type:e,name:g[e][m][0],alias:g[e][m][1]}),12<=d.length)break}if(12<=d.length)break}a.outputResults(d)}else a.outputResults([])}).on("blur",function(){var a=$(this);
setTimeout(function(){a.siblings("#sitesearch-results").hide()},200)})}},b=$.localDb("/json/",12);$("#sitesearch").on("focus",function(){b.load(["searchdata"],a.appMain)});$.fn.disableBlock=function(a){return"on"==a?this.each(function(){$(this).prevAll(".table-disabled").css({visibility:"visible"})}):"off"==a?this.each(function(){$(this).prevAll(".table-disabled").css({visibility:"hidden"})}):this.each(function(){$(this).wrap('<div class="table-wrap" />').before('<div class="table-disabled" />')})}});
$(window).load(function(){$(".pki, .pkg").each(function(){var a=$(this);a.addClass(a.data("sprite"))})});